openapi: 3.0.0
info:
  title: Your API Title
  description: Description of your API
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local server
  - url: http://127.0.0.1:5001/caratrack-backend/us-central1/v1
    description: Firebase Function server

paths:
  /:
    get:
      summary: Root Endpoint
      description: Endpoint to check if the API is up and running.
      responses:
        "200":
          description: API is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hii, i am there

  /users/signup:
    post:
      summary: User Signup
      description: Endpoint for user signup.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: yourpassword
      responses:
        "200":
          description: User signed up successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User signed up successfully
        "400":
          description: Bad request, invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email or password
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
